/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataRouteImport } from './routes/data'
import { Route as EnergyRouteImport } from './routes/energy'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as InvestigateMachineIdRouteImport } from './routes/investigate.$machineId'
import { Route as MachinesMachineIdRouteImport } from './routes/machines.$machineId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyRoute = EnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateMachineIdRoute = InvestigateMachineIdRouteImport.update({
  id: '/investigate/$machineId',
  path: '/investigate/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesMachineIdRoute = MachinesMachineIdRouteImport.update({
  id: '/$machineId',
  path: '/$machineId',
  getParentRoute: () => MachinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/energy': typeof EnergyRoute
  '/investigations': typeof InvestigationsRoute
  '/machines': typeof MachinesRouteWithChildren
  '/operations': typeof OperationsRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulate': typeof SimulateRoute
  '/investigate/$machineId': typeof InvestigateMachineIdRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/energy': typeof EnergyRoute
  '/investigations': typeof InvestigationsRoute
  '/machines': typeof MachinesRouteWithChildren
  '/operations': typeof OperationsRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulate': typeof SimulateRoute
  '/investigate/$machineId': typeof InvestigateMachineIdRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/energy': typeof EnergyRoute
  '/investigations': typeof InvestigationsRoute
  '/machines': typeof MachinesRouteWithChildren
  '/operations': typeof OperationsRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulate': typeof SimulateRoute
  '/investigate/$machineId': typeof InvestigateMachineIdRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/energy'
    | '/investigations'
    | '/machines'
    | '/operations'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/simulate'
    | '/investigate/$machineId'
    | '/machines/$machineId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data'
    | '/energy'
    | '/investigations'
    | '/machines'
    | '/operations'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/simulate'
    | '/investigate/$machineId'
    | '/machines/$machineId'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/energy'
    | '/investigations'
    | '/machines'
    | '/operations'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/simulate'
    | '/investigate/$machineId'
    | '/machines/$machineId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  EnergyRoute: typeof EnergyRoute
  InvestigationsRoute: typeof InvestigationsRoute
  MachinesRoute: typeof MachinesRouteWithChildren
  OperationsRoute: typeof OperationsRoute
  QualityRoute: typeof QualityRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SimulateRoute: typeof SimulateRoute
  InvestigateMachineIdRoute: typeof InvestigateMachineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy': {
      id: '/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof EnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate/$machineId': {
      id: '/investigate/$machineId'
      path: '/investigate/$machineId'
      fullPath: '/investigate/$machineId'
      preLoaderRoute: typeof InvestigateMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$machineId': {
      id: '/machines/$machineId'
      path: '/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof MachinesMachineIdRouteImport
      parentRoute: typeof MachinesRoute
    }
  }
}

interface MachinesRouteChildren {
  MachinesMachineIdRoute: typeof MachinesMachineIdRoute
}

const MachinesRouteChildren: MachinesRouteChildren = {
  MachinesMachineIdRoute: MachinesMachineIdRoute,
}

const MachinesRouteWithChildren = MachinesRoute._addFileChildren(
  MachinesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  EnergyRoute: EnergyRoute,
  InvestigationsRoute: InvestigationsRoute,
  MachinesRoute: MachinesRouteWithChildren,
  OperationsRoute: OperationsRoute,
  QualityRoute: QualityRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SimulateRoute: SimulateRoute,
  InvestigateMachineIdRoute: InvestigateMachineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
